### PR TITLE
xbee: update for zigpy changes

### LINKED ISSUE #161: Refactor to remove code duplication for devices that have multiple versions

### PR DESCRIPTION
**Pull request by Shulyaka**
1. Fixed deserialization to account for zigpy changes. This part appears to be just like #192, but also accounts for the serial data cluster. If you decide to first merge #192 then I can rebase my code.
2. Merged common code for xbee and xbee3 into a common class to reduce code duplication and allow easier maintainability (hopefully). Partially closes #161

### CODE REVIEW

**Comment by Shulyaka** [comment]
I also have plans to support analog input, PWM and internal temperature sensor.
I also tried to dynamically get pin configuration on startup by issuing remote AT commands in __init__ but found it too tricky (the zigpy_xbee application api needed for remote_at is not yet initialized at that point).

**Comment by dmulcahey** [comment]
@prairiesnpr @Adminiuga I am going to lean on you guys to review this... I don't have any xbee equiptment / knowledge.

**Comment by Adminiuga** [comment]
> I also tried to dynamically get pin configuration on startup by issuing remote AT commands in `__init__`

@Shulyaka nah, don't do in `__init__` Need to find a better way. We don't want to do any async in `__init__` and we also should do as less as possible in there. Maybe hook in in some of `handle_cluster` methods and do one time init.

**Comment by Adminiuga** [comment]
Overall looks good to me, but I did not test it with the actual devices. 
@prairiesnpr any chance you could test the changes whenever you have time?

Otherwise we trust @Shulyaka it is not in his interest to break Xbee :D

**Comment by Shulyaka** [comment]
> @Shulyaka nah, don't do in `__init__` Need to find a better way. We don't want to do any async in `__init__` and we also should do as less as possible in there. Maybe hook in in some of `handle_cluster` methods and do one time init.

Will try later after I finish everything else on my todo list)

**Comment by Shulyaka** [comment]
> Otherwise we trust @Shulyaka it is not in his interest to break Xbee :D

Well, currently it is broken anyway)

**Comment by dmulcahey** [comment]
@Shulyaka are we good to go here?

**Comment by Shulyaka** [comment]
From my perspective, yes

**Comment by Shulyaka** [comment]
Hi! I just noticed this PR was against master branch, not dev.....

**Comment by dmulcahey** [comment]
@Shulyaka merged it back... thanks again for pointing this out!

**Pull request merged**
