### PR TITLE
Add support for Aqara lumi b186acn01

### PR DESCRIPTION
**Pull request by dmulcahey**
fixes: #76

### CODE REVIEW

**Comment by darootler** [comment]
When will this fix be included in hass.io?

Regards
Richard

**Comment by Adminiuga** [comment]
I hope it gets into 0.95 which went beta this week.

**Comment by dmulcahey** [comment]
I’ll finish testing and package up a release on Saturday morning.

**Comment by darootler** [comment]
Patch seems fine and working. However there are 3 sensors added and just one of these is changing the state to „single“, „double“ and „long_press“.

The the other sensors are just reporting „unknown“ state.

Regards
Richard

**Comment by imellor** [comment]
On my HA, I only see the battery entity for this button. ALthough the triggers appear in the GUI, is this what was intended?

**Comment by dmulcahey** [comment]
Yep. Use device triggers or subscribe to zha_event for functionality

**Pull request merged**
