### PR TITLE
Add support for the SAGE Doorbell (AKA Echostar Bell)

### PR DESCRIPTION
**Pull request by bs42**
This quirk adds support for the SAGE Doorball (AKA Echostar Bell).

I only have the front door bell attached so I don't have the automation event code for the second doorbell.

### CODE REVIEW

**Comment by dmulcahey** [comment]
Lint and why is model info commented out?

**Comment by Adminiuga** [comment]
Can you please provide a brief summary what behavior this quirk changes/fixes?

**Comment by dmulcahey** [comment]
@Adminiuga its adding a device trigger

**Comment by bs42** [comment]
Model info was commented because it didn't match perfectly and I forgot to reenable it after testing the functionality.  This device has odd spacing in the name.  I have updated the patch to correct this issue.

Can you explain what you mean by "Lint"?  I didn't see reference to it in the contributors file.

**Comment by bs42** [comment]
This patch exposes the event from the doorbell to the automation.  Without it no events are seen by HA.

**Comment by bs42** [comment]
Nevermind about the lint thing, I see it under details of build.  Will fix.

**Comment by Adminiuga** [comment]
ok, so it's a device automation trigger, not ZHA_EVENTS, cause those work without quirk.

Shouldn't there be two triggers? There're two events: for the front door and back door???

**Comment by dmulcahey** [comment]
From the PR descripton: “ I only have the front door bell attached so I don't have the automation event code for the second doorbell.”

**Comment by Adminiuga** [comment]
it's sends an `off` command. Im trying to find more info in discord when i posted it

**Comment by bs42** [comment]
It actually only sends the 1 event, here's an example that was retrieved from watching zha_events as I was working on the quirk:

Event 1 fired 2:00 PM:
{
    "event_type": "zha_event",
    "data": {
        "unique_id": "00:08:89:00:01:d9:ad:32:18:0x0006",
        "device_ieee": "00:08:89:00:01:d9:ad:32",
        "endpoint_id": 18,
        "cluster_id": 6,
        "command": "on",
        "args": []
    },
    "origin": "LOCAL",
    "time_fired": "2020-03-13T21:00:24.742149+00:00",
    "context": {
        "id": "7a837acf01844493822d88408e48856b",
        "parent_id": null,
        "user_id": null
    }
}

**Comment by tube0013** [comment]
This?  https://discordapp.com/channels/330944238910963714/551843655682490399/679481458104074256

**Comment by Adminiuga** [comment]
Yep.

@bs42 -- very same event, but command is `off`

**Comment by bs42** [comment]
While I was watching zha_events in HA, I never saw an off command sent.  Only the event I posted.

**Comment by Adminiuga** [comment]
For BackDoor ringbell, it sends the Off command. You can rewire your Sage to confirm.

**Comment by bs42** [comment]
I don't understand the remaining lint issues, I've rechecked it against other existing modules and the syntax appears to be the same.  If you have any pointers I'd be happy to look.

**Comment by dmulcahey** [comment]
Sort the imports with isort

**Comment by Adminiuga** [comment]
Please, Please, Please add the second trigger for the back door bell.

**Comment by dmulcahey** [comment]
@Adminiuga LOL I won’t merge it without it

**Comment by bs42** [comment]
Sorting did change some things, some of the parameters weren't in alphabetical order, but the lint errors remain exactly the same.  I'm at a complete loss.

Does anyone actually have 2 doorbells?  I've never seen a house with more than one.

**Comment by dmulcahey** [comment]
@bs42 I just pushed a change that should fix your lint errors. Please add the additional trigger.

**Comment by bs42** [comment]
All done, changed to BUTTON_1 and BUTTON_2

**Pull request merged**
