### PR TITLE
Add WAXMANN leakSMART Water Sensor V2 quirk

### PR DESCRIPTION
**Pull request by presslab-us**
This sensor has a device type of TEMPERATURE_SENSOR and uses
an "Unstructured" Appliance Alert command to indicate water state.
This quirk emulates an IAS Zone cluster like a standard water sensor.
Battery level and temperature work without any changes.

### CODE REVIEW

**Comment by dmulcahey** [comment]
@brg468   FYI

**Comment by brg468** [comment]
Sorry for just now getting back to you on this...I just tested this out in the latest version of HA 0.98.0 and I’m still not having any luck getting a water event to show up. I re-added the device a couple times with the same result.

**Comment by brg468** [comment]
If it helps:

```
2019-08-29 14:22:51 DEBUG (MainThread) [homeassistant.components.zha.core.gateway] device - 0xe93c:00:22:a3:00:00:13:44:07 entering async_device_initialized - is_new_join: True
2019-08-29 14:22:51 DEBUG (MainThread) [homeassistant.components.zha.core.gateway] device - 0xe93c:00:22:a3:00:00:13:44:07 has joined the ZHA zigbee network
2019-08-29 14:22:51 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xe93c](leakSMART Water Sensor V2): started configuration
2019-08-29 14:22:51 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:ZDO](leakSMART Water Sensor V2): channel: 'async_configure' stage succeeded
2019-08-29 14:22:52 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0x0000]: bound 'basic' cluster: Status.SUCCESS
2019-08-29 14:22:52 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0x0000]: finished channel configuration
2019-08-29 14:22:52 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0xfc02]: bound 'manufacturer_specific' cluster: Status.SUCCESS
2019-08-29 14:22:52 ERROR (MainThread) [zigpy.zcl] [0xe93c:1:0xfc02] acceleration is not a valid attribute id
2019-08-29 14:22:52 WARNING (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0xfc02]: channel: 'async_configure' stage failed ex: object NoneType can't be used in 'await' expression
2019-08-29 14:22:52 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0x0402]: bound 'temperature' cluster: Status.SUCCESS
2019-08-29 14:22:53 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0x0000]: initializing channel: from_cache: False
2019-08-29 14:22:53 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0x0000]: channel: 'async_configure' stage succeeded
2019-08-29 14:22:53 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0x0001]: bound 'power' cluster: Status.SUCCESS
2019-08-29 14:22:53 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0x0402]: reporting 'measured_value' attr on 'temperature' cluster: 30/900/50: Result: '[[<ConfigureReportingResponseRecord status=Status.SUCCESS>]]'
2019-08-29 14:22:53 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0x0402]: finished channel configuration
2019-08-29 14:22:53 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0x0402]: channel: 'async_configure' stage succeeded
2019-08-29 14:22:54 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0x0001]: reporting 'battery_voltage' attr on 'power' cluster: 3600/10800/1: Result: '[[<ConfigureReportingResponseRecord status=Status.SUCCESS>]]'
2019-08-29 14:22:55 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0x0001]: reporting 'battery_percentage_remaining' attr on 'power' cluster: 3600/10800/1: Result: '[[<ConfigureReportingResponseRecord status=Status.SUCCESS>]]'
2019-08-29 14:22:55 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0x0001]: finished channel configuration
2019-08-29 14:22:55 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0x0001]: channel: 'async_configure' stage succeeded
2019-08-29 14:22:55 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xe93c](leakSMART Water Sensor V2): completed configuration
2019-08-29 14:22:55 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xe93c](leakSMART Water Sensor V2): stored in registry: ZhaDeviceEntry(name='unk_manufacturer unk_model', ieee='00:22:a3:00:00:13:44:07', last_seen=1567102975.371935)
2019-08-29 14:22:55 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xe93c](leakSMART Water Sensor V2): started initialization
2019-08-29 14:22:55 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:ZDO](leakSMART Water Sensor V2): entry loaded from storage: ZhaDeviceEntry(name='unk_manufacturer unk_model', ieee='00:22:a3:00:00:13:44:07', last_seen=1567102975.371935)
2019-08-29 14:22:55 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:ZDO](leakSMART Water Sensor V2): channel: 'async_initialize' stage succeeded
2019-08-29 14:22:55 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0xfc02]: initializing channel: from_cache: False
2019-08-29 14:22:55 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0xfc02]: channel: 'async_initialize' stage succeeded
2019-08-29 14:22:56 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0x0402]: initializing channel: from_cache: False
2019-08-29 14:22:56 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0x0402]: channel: 'async_initialize' stage succeeded
2019-08-29 14:22:56 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0x0000]: initializing channel: from_cache: False
2019-08-29 14:22:56 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0x0000]: channel: 'async_initialize' stage succeeded
2019-08-29 14:22:59 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0x0001]: initializing channel: from_cache: False
2019-08-29 14:22:59 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0x0001]: channel: 'async_initialize' stage succeeded
2019-08-29 14:22:59 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xe93c](leakSMART Water Sensor V2): power source: Battery or Unknown
2019-08-29 14:22:59 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xe93c](leakSMART Water Sensor V2): completed initialization
```

**Comment by presslab-us** [comment]
```
2019-08-29 14:22:52 ERROR (MainThread) [zigpy.zcl] [0xe93c:1:0xfc02] acceleration is not a valid attribute id
2019-08-29 14:22:52 WARNING (MainThread) [homeassistant.components.zha.core.channels] [0xe93c:1:0xfc02]: channel: 'async_configure' stage failed ex: object NoneType can't be used in 'await' expression
```

Interesting debug log!  This part seems really weird to me, where does "accelleration" come from?  I didn't see this error by the way.

Are you sure it's using the quirk?  In the ZHA Configuration panel, after selecting the device, you should see `Quirk: zhaquirks.waxman.leaksmart.WAXMANleakSMARTv2` below `Power Source:
Battery or Unknown`

**Comment by brg468** [comment]
I don't see any mention of the quirk in the config panel. Is there something I need to do to enable the quirk? 

It also seems like it's not doing a full re-load after I un-pair/re-pair. I've tried removing the entry from .storage but that didn't seem to help.

`2019-08-29 14:22:55 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xe93c](leakSMART Water Sensor V2): stored in registry: ZhaDeviceEntry(name='unk_manufacturer unk_model', ieee='00:22:a3:00:00:13:44:07', last_seen=1567102975.371935)`

**Comment by Adminiuga** [comment]
to fully reload, you need to remove device 1st from ZHA config panel -> pick the device -> remove and give it a few

**Comment by brg468** [comment]
I’ve tried that I think. Unpaired then restarted HA before and after editing the zha.storage file. Seems to keep re-appearing.

**Comment by presslab-us** [comment]
There is a separate database containing the ZHA devices.  It's not very easy to delete things from there.  I haven't had any issues using the Configuration panel to do it.

**Comment by brg468** [comment]
So here’s a thought, I’m thinking I don’t have the V2 of this sensor.. Maybe V1 doesn’t pair the same.

**Comment by presslab-us** [comment]
Yeah it must match the signature exactly or it won't do the quirk.  But your logs show V2? If you turn on 'zigpy' debug log look for 'Discovered endpoint information', 'Manufacturer', and 'Model'.

**Comment by brg468** [comment]
```
2019-08-29 18:45:11 DEBUG (MainThread) [homeassistant.components.zha.api] Read attribute for: cluster_id: [0] cluster_type: [in] endpoint_id: [1] attribute: [4] manufacturer: [None] response: [WAXMAN] failure: [{}]
2019-08-29 18:45:20 DEBUG (MainThread) [homeassistant.components.zha.api] Read attribute for: cluster_id: [0] cluster_type: [in] endpoint_id: [1] attribute: [5] manufacturer: [None] response: [leakSMART Water Sensor V2] failure: [{}]
```

**Comment by brg468** [comment]
I have 2 of these sensors. Just paired the other one and am having the same result, no quirks.

**Comment by Adminiuga** [comment]
Enable zigpy debug and post debug log of pairing here. Need to see active endpoint and match descriptor responses

**Comment by brg468** [comment]
```
2019-08-30 14:09:29 DEBUG (MainThread) [zigpy.zcl] [0x32ae:1:0x0001] ZCL request 0x000a: [[<Attribute attrid=32 value=<TypeValue type=uint8_t, value=29>>]]
2019-08-30 14:09:29 DEBUG (MainThread) [zigpy.zcl] [0x32ae:1:0x0001] Attribute report received: battery_voltage=29
2019-08-30 14:09:29 INFO (MainThread) [zigpy.application] Device 0xb713 (00:22:a3:00:00:13:44:07) joined the network
2019-08-30 14:09:29 INFO (MainThread) [zigpy.device] [0xb713] Requesting 'Node Descriptor'
2019-08-30 14:09:29 DEBUG (MainThread) [zigpy.zdo] [0xb713:zdo] ZDO request ZDOCmd.Device_annce: [0xb713, 00:22:a3:00:00:13:44:07, 128]
2019-08-30 14:09:30 INFO (MainThread) [zigpy.device] [0xb713] Node Descriptor: <Optional byte1=2 byte2=64 mac_capability_flags=128 manufacturer_code=4411 maximum_buffer_size=82 maximum_incoming_transfer_size=82 server_mask=0 maximum_outgoing_transfer_size=82 descriptor_capability_field=0>
2019-08-30 14:09:30 INFO (MainThread) [zigpy.device] [0xb713] Discovering endpoints
2019-08-30 14:09:31 INFO (MainThread) [zigpy.device] [0xb713] Discovered endpoints: [1]
2019-08-30 14:09:31 INFO (MainThread) [zigpy.endpoint] [0xb713:1] Discovering endpoint information
2019-08-30 14:09:33 INFO (MainThread) [zigpy.endpoint] [0xb713:1] Discovered endpoint information: <SimpleDescriptor endpoint=1 profile=260 device_type=770 device_version=0 input_clusters=[0, 1, 3, 1026, 2818, 64514] output_clusters=[3, 25]>
2019-08-30 14:09:33 DEBUG (MainThread) [zigpy.zcl] [0xfc06:1:0x0402] ZCL request 0x000a: [[<Attribute attrid=0 value=<TypeValue type=int16s, value=2400>>]]
2019-08-30 14:09:33 DEBUG (MainThread) [zigpy.zcl] [0xfc06:1:0x0402] Attribute report received: measured_value=2400
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.endpoint] [0xb713:1] Manufacturer: WAXMAN
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.endpoint] [0xb713:1] Model: leakSMART Water Sensor V2
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Checking quirks for WAXMAN leakSMART Water Sensor V2 (00:22:a3:00:00:13:44:07)
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.waxman.leaksmart.WAXMANleakSMARTv2'>
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Fail because input cluster mismatch on at least one endpoint
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zigpy.quirks.smartthings.SmartthingsMultiPurposeSensor'>
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Fail because device_type mismatch on at least one endpoint
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.gledopto.soposhgu10.SoposhGU10'>
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Fail because endpoint list mismatch: {11, 13} {1}
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.lutron.lzl4bwhl01remote.LutronLZL4BWHL01Remote2'>
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Fail because profile_id mismatch on at least one endpoint
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.netvox.z308e3ed.Z308E3ED'>
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Fail because device_type mismatch on at least one endpoint
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.osram.a19twhite.A19TunableWhite'>
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Fail because endpoint list mismatch: {3} {1}
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.philips.rwl021.PhilipsRWL021'>
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Fail because endpoint list mismatch: {1, 2} {1}
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.smartthings.tag_v4.SmartThingsTagV4'>
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Fail because device_type mismatch on at least one endpoint
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.xbee.xbee3_io.XBee3Sensor'>
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Fail because endpoint list mismatch: {232, 230} {1}
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.xbee.xbee_io.XbeeSensor'>
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Fail because endpoint list mismatch: {232, 230} {1}
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.xiaomi.mija.smoke.MijiaHoneywellSmokeDetectorSensor'>
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Fail because device_type mismatch on at least one endpoint
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'bellows.zigbee.application.EZSPCoordinator'>
2019-08-30 14:09:34 DEBUG (MainThread) [zigpy.quirks.registry] Fail because device_type mismatch on at least one endpoint
2019-08-30 14:09:34 DEBUG (MainThread) [homeassistant.components.zha.core.gateway] device - 0xb713:00:22:a3:00:00:13:44:07 entering async_device_initialized - is_new_join: True
2019-08-30 14:09:34 DEBUG (MainThread) [homeassistant.components.zha.core.gateway] device - 0xb713:00:22:a3:00:00:13:44:07 has joined the ZHA zigbee network
2019-08-30 14:09:34 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xb713](leakSMART Water Sensor V2): started configuration
2019-08-30 14:09:34 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:ZDO](leakSMART Water Sensor V2): channel: 'async_configure' stage succeeded
2019-08-30 14:09:35 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:1:0xfc02]: bound 'manufacturer_specific' cluster: Status.SUCCESS
2019-08-30 14:09:35 ERROR (MainThread) [zigpy.zcl] [0xb713:1:0xfc02] acceleration is not a valid attribute id
2019-08-30 14:09:35 WARNING (MainThread) [homeassistant.components.zha.core.channels] [0xb713:1:0xfc02]: channel: 'async_configure' stage failed ex: object NoneType can't be used in 'await' expression
2019-08-30 14:09:35 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:1:0x0402]: bound 'temperature' cluster: Status.SUCCESS
2019-08-30 14:09:35 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:1:0x0001]: bound 'power' cluster: Status.SUCCESS
2019-08-30 14:09:36 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:1:0x0000]: bound 'basic' cluster: Status.SUCCESS
2019-08-30 14:09:36 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:1:0x0000]: finished channel configuration
2019-08-30 14:09:36 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:1:0x0402]: reporting 'measured_value' attr on 'temperature' cluster: 30/900/50: Result: '[[<ConfigureReportingResponseRecord status=Status.SUCCESS>]]'
2019-08-30 14:09:36 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:1:0x0001]: reporting 'battery_voltage' attr on 'power' cluster: 3600/10800/1: Result: '[[<ConfigureReportingResponseRecord status=Status.SUCCESS>]]'
2019-08-30 14:09:36 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:1:0x0402]: finished channel configuration
2019-08-30 14:09:36 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:1:0x0402]: channel: 'async_configure' stage succeeded
2019-08-30 14:09:37 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:1:0x0000]: initializing channel: from_cache: False
2019-08-30 14:09:37 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:1:0x0000]: channel: 'async_configure' stage succeeded
2019-08-30 14:09:37 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:1:0x0001]: reporting 'battery_percentage_remaining' attr on 'power' cluster: 3600/10800/1: Result: '[[<ConfigureReportingResponseRecord status=Status.SUCCESS>]]'
2019-08-30 14:09:37 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:1:0x0001]: finished channel configuration
2019-08-30 14:09:37 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:1:0x0001]: channel: 'async_configure' stage succeeded
2019-08-30 14:09:37 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xb713](leakSMART Water Sensor V2): completed configuration
2019-08-30 14:09:37 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xb713](leakSMART Water Sensor V2): stored in registry: ZhaDeviceEntry(name='unk_manufacturer unk_model', ieee='00:22:a3:00:00:13:44:07', last_seen=1567188577.042949)
2019-08-30 14:09:37 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xb713](leakSMART Water Sensor V2): started initialization
2019-08-30 14:09:37 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:ZDO](leakSMART Water Sensor V2): entry loaded from storage: ZhaDeviceEntry(name='unk_manufacturer unk_model', ieee='00:22:a3:00:00:13:44:07', last_seen=1567188577.042949)
2019-08-30 14:09:37 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:ZDO](leakSMART Water Sensor V2): channel: 'async_initialize' stage succeeded
2019-08-30 14:09:37 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:1:0xfc02]: initializing channel: from_cache: False
2019-08-30 14:09:37 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:1:0xfc02]: channel: 'async_initialize' stage succeeded
2019-08-30 14:09:38 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:1:0x0000]: initializing channel: from_cache: False
2019-08-30 14:09:38 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:1:0x0000]: channel: 'async_initialize' stage succeeded
2019-08-30 14:09:38 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:1:0x0402]: initializing channel: from_cache: False
2019-08-30 14:09:38 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:1:0x0402]: channel: 'async_initialize' stage succeeded
2019-08-30 14:09:41 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:1:0x0001]: initializing channel: from_cache: False
2019-08-30 14:09:41 DEBUG (MainThread) [homeassistant.components.zha.core.channels] [0xb713:1:0x0001]: channel: 'async_initialize' stage succeeded
2019-08-30 14:09:41 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xb713](leakSMART Water Sensor V2): power source: Battery or Unknown
2019-08-30 14:09:41 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0xb713](leakSMART Water Sensor V2): completed initialization
```

**Comment by presslab-us** [comment]
Looks like your device is slightly different than mine.
Yours:
<SimpleDescriptor endpoint=1 profile=260 device_type=770 device_version=0 input_clusters=[0, 1, 3, 1026, 2818, 64514] output_clusters=[3, 25]>
Mine:
<SimpleDescriptor endpoint=1 profile=260 device_type=770 device_version=0 input_clusters=[0, 1, 3, 32, 1026, 2818, 64514] output_clusters=[3, 25]>

Mine has the "PollControl cluster, and yours does not.  I have updated my firmware to the latest, so you probably have an older version.

I'd guess that with a slight modification this quirk would work for your device as well.

**Comment by brg468** [comment]
I removed PollControl.cluster_id from the quirk and now it works! Is there a way to make that cluster optional when checking the quirk for compatibility? 

```
        'models_info': [
            ('WAXMAN', 'leakSMART Water Sensor V2'),
        ],
        'endpoints': {
            1: {
                'profile_id': zha.PROFILE_ID,
                'device_type': zha.DeviceType.TEMPERATURE_SENSOR,
                'input_clusters': [
                    Basic.cluster_id,
                    PowerConfiguration.cluster_id,
                    Identify.cluster_id,
                    #PollControl.cluster_id,
                    TemperatureMeasurement.cluster_id,
                    ApplianceEventAlerts.cluster_id,
                    MANUFACTURER_SPECIFIC_CLUSTER_ID
                ],
                'output_clusters': [
                    Identify.cluster_id,
                    Ota.cluster_id
                ],
            },
        }
    }

    replacement = {
        'endpoints': {
            1: {
                'profile_id': zha.PROFILE_ID,
                'device_type': zha.DeviceType.TEMPERATURE_SENSOR,
                'input_clusters': [
                    Basic.cluster_id,
                    PowerConfiguration.cluster_id,
                    Identify.cluster_id,
                    #PollControl.cluster_id,
                    TemperatureMeasurement.cluster_id,
                    WAXMANApplianceEventAlerts,
                    EmulatedIasZone
                ],
                'output_clusters': [
                    Identify.cluster_id,
                    Ota.cluster_id
                ],
            },
        }
    }
```

**Comment by presslab-us** [comment]
Great!  I asked this question before and I think the best way to handle this is to create another class, but with the `PollControl` cluster removed.  Something like `class WAXMANleakSMARTv2_2(CustomDevice):` perhaps?  Just add the new class into that same file.  Be sure to update the comment with the "32, " removed.  And then a pull request would be certainly welcomed.  :smiley:

**Comment by presslab-us** [comment]
Thanks for your contribution @brg468!  Here is a link to your pull request for posterity. https://github.com/dmulcahey/zha-device-handlers/pull/143

**Pull request merged**
