### PR TITLE
Add lutron remote device automation buttons

### PR DESCRIPTION
**Pull request by bballwiz5**

### CODE REVIEW

**Comment by dmulcahey** [comment]
@bballwiz5 thx. I’ll merge once the lint issue is fixed.

**Comment by dmulcahey** [comment]
@bballwiz5 any chance you can fix the lint issue so I can merge this and produce a release?

**Comment by dmulcahey** [comment]
@bballwiz5 nevermind... I did it

**Comment by bballwiz5** [comment]
Sorry about that, traveling without access to my computer. Thanks for fixing it!

________________________________

**Pull request merged**
