### PR TITLE
Add Konke motion sensors

### PR DESCRIPTION
**Pull request by vigonotion**
The Konke motion sensor only triggers an event on motion in the IasZone, but it is never going off.
This quirk adds a timed callback to turn the zone off again, and adds an occupancy cluster as well.

It seems like there are three device variants:
`(KONKE, "3AFE28010402000D"), (KONKE, "3AFE14010402000D"), (KONKE, "3AFE27010402000D`
I own the first one and it works fine. Got the other device infos from [zigbee-herdsman-converters](https://github.com/Koenkk/zigbee-herdsman-converters/blob/764eb3fff57365e1c97ee0c98007b6cb797048c7/devices.js).

i chose `MOTION_TIME = 60` and `OCCUPANCY_TIME = 600` as timeouts for the callbacks, as there was no common timeout I found in the other sensors.

The quirk is based on the Trust ZPIR-8000 and the lumi.sensor_motion quirks.

### CODE REVIEW

**Comment by vigonotion** [comment]
I don't know how to fix the last ci error
```
would reformat /home/travis/build/dmulcahey/zha-device-handlers/zhaquirks/konke/__init__.py

All done! 💥 💔 💥

1 file would be reformatted, 104 files would be left unchanged.

ERROR: InvocationError for command /home/travis/build/dmulcahey/zha-device-handlers/script/check_format (exited with code 1)
```

there is no real information on what is wrong in that file

**Comment by dmulcahey** [comment]
Run black on the code.

**Comment by vigonotion** [comment]
I did that in f4b0331:
```
(venv3.6) tom@toms-notebook:~/Git/zha-device-handlers (vi/konke-motion)$ black zhaquirks/konke/*.py
All done! ✨ 🍰 ✨
2 files left unchanged.
```
it's already formatted using black

**Comment by dmulcahey** [comment]
I opened a pr against your branch with the needed change

**Comment by vigonotion** [comment]
perfect, works now. Thanks for the help

**Pull request merged**
